### PR TITLE
Dunner as Go module

### PR DESCRIPTION
**Pull request by apoorvam**
This builds Dunner as [GoModule](https://github.com/golang/go/wiki/Modules) and removes the use of dep. 

Pros: 
* No external dependency to install `dep`
* Project does not have to be in GOPATH. This becomes useful in containers.

Cons: 
* GoModules has to be set explicitly since its not yet default, in travis as: `GO111MODULE=on`

### CODE REVIEW

**Review by PratikDhanave — APPROVED** [review]
awesome work

**Review by agentmilindu — APPROVED** [review]

**Comment by agentmilindu** [comment]
@apoorvam  Can you look into why the Travis Script failed?

**Comment by apoorvam** [comment]
Its failing for an issue which is fixed in different PR. Build will pass if this PR can be merged first: https://github.com/leopardslab/dunner/pull/170/files @agentmilindu

**Comment by apoorvam** [comment]
Wdyt about using go module vs dep? @agentmilindu

**Comment by agentmilindu** [comment]
@apoorvam I strongly agree with moving from Dep to Mod

**Pull request merged**
